image: Visual Studio 2019

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  LDFLAGS: -static-libgcc -static-libstdc++
  matrix:
    - arch: x86
      MSYSTEM: MINGW32
      CC: ccache i686-w64-mingw32-gcc
      CXX: ccache i686-w64-mingw32-g++
      CFLAGS: -msse
    - arch: x64
      MSYSTEM: MINGW64
      CC: ccache x86_64-w64-mingw32-gcc
      CXX: ccache x86_64-w64-mingw32-g++

install:
  - set "PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%"
  - set MSYS2_PATH_TYPE=inherit
  # Download ninja and meson
  - pacman -Syyuu --ask=20 --noconfirm --noprogressbar --needed
  - pacman -Sy --ask=20 --noconfirm --noprogressbar --needed mingw-w64-x86_64-ninja mingw-w64-x86_64-meson

build_script:
  - echo Building on %arch%
  - set "CFLAGS=-static %CFLAGS%"
  - set "CXXFLAGS=-static %CXXFLAGS%"
  - cd libvmaf
  - meson setup --backend=ninja --default-library=static --buildtype=release --prefix="%CD%/install" build
  - ninja -vC build install

test_script:
  - ninja -vC build test

after_build:
  - 7z a vmaf-win-%arch%.zip install\**\*.*

artifacts:
  - path: libvmaf\**\*.zip
  - path: libvmaf\build\src\libvmaf*.*
  - path: libvmaf\build\tools\*vmaf*.exe
  - path: libvmaf\build\meson-logs\*.txt

cache:
  - 'C:\msys64\home\appveyor\.ccache'
  - 'C:\msys64\var\cache\pacman\pkg'
